[sinks.datadog_logs]
title = "Datadog Logs"
beta = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
function_category = "transmit"
healthcheck = true
input_types = ["log"]
service_providers = ["Datadog"]
write_to_description = "[Datadog's][urls.datadog] logs"

<%= render("_partials/_component_options.toml", type: "sink", name: "datadog_logs") %>

<%= render("_partials/_buffer_options.toml", namespace: "sinks.datadog_logs.options") %>

[sinks.datadog_logs.options.api_key]
type = "string"
common = true
examples = ["${DATADOG_API_KEY_ENV_VAR}", "ef8d5de700e7989468166c40fc8a0ccd"]
required = true
description = "Datadog [API key](https://docs.datadoghq.com/api/?lang=bash#authentication)"

[sinks.datadog_logs.options.encoding]
type = "string"
category = "requests"
common = true
required = true
description = """\
The encoding format used to serialize the events before outputting.\
"""

[sinks.datadog_logs.options.encoding.enum]
json = "Each event is encoded into JSON."
text = "Each event is encoded into text via the `message` key."

[sinks.datadog_logs.options.endpoint]
type = "string"
common = true
required = false
default = "intake.logs.datadoghq.com:10516"
examples = ["127.0.0.1:8080", "example.com:12345"]
description = "The endpoint to stream logs to."

<%= render("_partials/_tls_options.toml", namespace: "sinks.datadog_logs.options", can_enable: true, can_verify: true) %>
