[<%= namespace %>.encoding.format]
type = "string"
common = true
required = true
description = """\
The encoding format used to serialize the events before outputting.\
"""

[<%= namespace %>.encoding.only_fields]
type = "[string]"
required = false
examples = ["timestamp", "message", "host"]
description = """\
Limit the sink to only encoding the specified labels.\
"""

[<%= namespace %>.encoding.except_fields]
type = "[string]"
required = false
examples = ["timestamp", "message", "host"]
description = """\
Prevent the sink from encoding the specified labels.\
"""
